config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :projects
  resources :contracts

  get 'proj', to: 'contracts#new'
  get 'welcome/proj', to: 'contracts#new'
  get 'users/proj', to: 'contracts#new'
  get 'proj/proj', to: 'contracts#new'
  get 'contracts/proj', to: 'contracts#new'
  get 'projects/proj', to: 'contracts#new'
  get 'projs', to: 'projects#new'

  root 'welcome#index'

  

end

app/models/contract.rb
class Contract < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!, except: [:index]
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:email, :password, :password_confirmation, :name, :ethid]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
    }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
def new
	@projects = Project.all
end
def create
  back_amount = contract_params["back"]
  campaign_id = contract_params["projid"]
  data = `serpent encode_datalist "'1' '#{campaign_id}'"`
  secret = "6ad0b58c60ea450544775b0f468097e140b709c041fe23f2a7ae2138dc691096"
  contract_address = "ab9998252af519f64e25668c5145ab4647d30e74"
  gas_price  = "10000000000000000"
  gas_amount = "4000"
  #transaction_str = contract_address + " " + back_amount + " " + gas_price + " " + gas_amount + " " secret + " " + data
  transaction_str = "curl -X POST --data '{\"method\":\"transact\", \"params\":{\"sec\":\"#{secret}\",\"xValue\":\"#{back_amount}\",\"aDest\":\"#{contract_address}\",\"bData\":\"#{data}\",\"xGas\":\"#{gas_amount}\",\"xGasPrice\":\"#{gas_price}\"}, \"jsonrpc\":\"2.0\", \"id\":2}'"
  #`/home/colin/Documents/cpp-etherem/build/eth/eth transact #{transaction_str}`
  `transaction_str`
  @contract = Contract.new(contract_params)
  @contract.save
  if @contract.save
  	@contract.custid = current_user.id
  	@proj = Project.find(@contract.projid)
  	if @proj.min > @contract.back
  		@contract.destroy
  	else
    @proj.pl = @proj.pl + @contract.back
  	@proj.backed = @proj.backed + 1
  	@contract.save
  	@proj.save
  	redirect_to @contract
  	end
  end
  
end

def show
  @contract = Contract.find(params[:id])
end

private
  def contract_params
    params.require(:contract).permit(:custid, :projid, :tx, :back)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
def new
end
def create
  target_amount = contract_params["target"]
  user_id = current_user.ethid
  seconds = contract_params["exp"] - Time.now
  data = `serpent encode_datalist "'0' '#{user_id}' '#{seconds}' 'target_amount'"`
  #curl -X POST --data '{"method":"transact","params":{"xEndowment":"","bCode":"300580600b60003960105860026001576000f1","sec":"6ad0b58c60ea450544775b0f468097e140b709c041fe23f2a7ae2138dc691096","xGas":"700","xGasPrice":"10000000000000"},"jsonrpc":"2.0","id":"1"}' http://localhost:8080
  
  secret = "6ad0b58c60ea450544775b0f468097e140b709c041fe23f2a7ae2138dc691096"
  contract_address = "ab9998252af519f64e25668c5145ab4647d30e74"
  gas_price  = "10000000000000000"
  gas_amount = "4000"
  transaction_str = "curl -X POST --data '{\"method\":\"transact\", \"params\":{\"sec\":\"#{secret}\",\"xValue\":\"0\",\"aDest\":\"#{contract_address}\",\"bData\":\"#{data}\",\"xGas\":\"#{gas_amount}\",\"xGasPrice\":\"#{gas_price}\"}, \"jsonrpc\":\"2.0\", \"id\":2}'"
  #transaction_str = contract_address + " " + target_amount + " " + gas_price + " " + gas_amount + " " secret + " " + data
  #{`/home/colin/Documents/cpp-etherem/build/eth/eth transact #{transaction_str}`
  `transaction_str`
  @project = Project.new(project_params)
  @project.save
  if @project.save
  	@project.backed = 0
    @project.pl = 0
  end
  @project.save
  redirect_to @project
end

def show
  @project = Project.find(params[:id])
end

private
  def project_params
    params.require(:project).permit(:title, :desc, :backed, :roll, :exp, :min, :target, :ethercode, :pl)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 
  prepend_before_filter :require_no_authentication, only: [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, only: [:edit, :update, :destroy]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  def update_needs_confirmation?(resource, previous)
    super
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    super
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash=nil)
    super
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    super
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    super
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    super
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    super
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    super
  end

  def sign_up_params
    super
  end

  def account_update_params
    super
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	  @se = user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contracts/new.html.erb
<html lang="en" ng-app="Dashboard" class="ng-scope"><head><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-animate){display:none !important;}ng\:form{display:block;}</style>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Dashboard</title>

  <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="/assets/fonts/font-awesome.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/dashboard/dashboard.css">
  <link rel="stylesheet" type="text/css" href="css/themes/blue.css">
  <!--
  <link rel="stylesheet" type="text/css" href="css/themes/green.css">
  <link rel="stylesheet" type="text/css" href="css/themes/red.css">
  -->

  <script type="text/javascript" src="js/angular.min.js"></script>
  <script type="text/javascript" src="js/angular-cookies.js"></script>
  <script type="text/javascript" src="js/ng-bootstrap-tpls.min.js"></script>
  <script type="text/javascript" src="js/angular/bootstrap.js"></script>

</head>
<body ng-controller="MasterCtrl" class="ng-scope">

    <!-- Fixed navbar -->
      <div id="navigation" class="navbar navbar-default navbar-fixed-top" style="border-bottom: 3px solid #e7e7e7;">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><b>Backito</b></a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
          <li><%= link_to 'Home', welcome_index_path%></li>
            <li><%= link_to 'Edit', edit_user_registration_path%></li>
            <li   class="active"><%= link_to 'Projects', 'proj'%></li>
            
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>

              

        </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>


  <div id="page-wrapper" ng-class="{'active': toggle}" class="active">

    <!-- Sidebar -->

    <div id="sidebar-wrapper">
      <ul class="sidebar">
        <li class="sidebar-title"><span>CAMPAIGNS</span></li>
        <li class="sidebar-list">
          <a href="#">My Campaigns <span class="menu-icon fa fa-tachometer"></span></a>
        </li>
        <li class="sidebar-list">
          <a href="/projs">New Campaign<span class="menu-icon fa fa-tasks"></span></a>
        </li>
        <li class="sidebar-list">
          <a href="#">Settings <span class="menu-icon fa fa-cogs"></span></a>
        </li>
        <li class="sidebar-title separator"><span>QUICK LINKS</span></li>
        <li class="sidebar-list">
          <a href="#" target="_blank">Forums <span class="menu-icon fa fa-external-link"></span></a>
        </li>
      </ul>
      <div class="sidebar-footer">
        <div class="col-xs-4">
          <a href="https://github.com/prathamalag1994/hackmit" target="_blank">
            Github
          </a>
        </div>
        <div class="col-xs-4">
          <a href="#" target="_blank">
            About
          </a>
        </div>
        <div class="col-xs-4">
          <a href="#">
            Support
          </a>
        </div>
      </div>
    </div>

    <!-- End Sidebar -->

    <div id="content-wrapper">
      <div class="page-content">

        <!-- Header Bar -->

        <div class="row header">
          <div class="col-xs-12">
            <div class="meta pull-left">
              <div class="page">
                Dashboard
              </div>
              <div class="breadcrumb-links">
                Home / Dashboard
              </div>
            </div>
            <div class="user pull-right">
              <div class="item dropdown">
                <a href="#" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">
                  <img src="img/avatar.jpg">
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    Joe Bloggs
                  </li>
                  <li class="divider"></li>
                  <li class="link">
                    <a href="#">
                      Profile
                    </a>
                  </li>
                  <li class="link">
                    <a href="#">
                      Menu Item
                    </a>
                  </li>
                  <li class="link">
                    <a href="#">
                      Menu Item
                    </a>
                  </li>
                  <li class="divider"></li>
                  <li class="link">
                    <a href="#">
                      Logout
                    </a>
                  </li>
                </ul>               
              </div>
              <div class="item dropdown">
               <a href="#" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-bell-o"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    Notifications
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="#">Server Down!</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- End Header Bar -->


          <div class="row">
            <% @projects.each do |offer| %>
            <div class="col-lg-4 col-md-6 col-xs-12">
              <div class="widget">
                <div class="widget-body">
                  <div class="widget-icon green pull-left">
                    <i class="fa fa-users"></i>
                  </div>
                  <div class="widget-content pull-left">
                    <div class="title"><%= offer.title %></div>
                    <div class="comment text-muted">Pledged: <%= offer.pl %></div>
                    <div class="comment text-muted">Target: <%= offer.target %></div>
                    <div class="comment text-muted">Expires: <%= offer.exp %></div>
                    <hr />

                  </div><%= offer.desc %><div class="clearfix"></div>
                <br />
                  <form accept-charset="UTF-8" action="/contracts" method="post"><div style="display:none"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" /></div>                     
                    <input id="contract_projid" name="contract[projid]" type="hidden" value="<%= offer.id %>" />
                    <input id="contract_back" name="contract[back]" type="number" style="padding:5px 10px 5px 10px;" placeholder="Back amount" >
                    <button type="submit" class="btn btn-default">Back Campaign</button>
                  </form>                  
                </div>

              </div>
            </div>
            <% end %>
          </div>


          <!--
          <div class="row">
            <div class="col-lg-6">
              <div class="widget">
                <div class="widget-title">
                  <i class="fa fa-tasks"></i> Servers
                  <a href="#" class="pull-right">Manage</a>
                </div>
                <div class="widget-body medium no-padding">
                  <div class="table-responsive">
                    <table class="table">
                      <tbody>
                        <tr><td>RDVMPC001</td><td>238.103.133.37</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                        <tr><td>RDVMPC002</td><td>68.66.63.170</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                        <tr><td>RDVMPC003</td><td>76.117.212.33</td><td><span tooltip="Server Down!" class="text-danger ng-scope"><i class="fa fa-warning"></i></span></td></tr>
                        <tr><td>RDPHPC001</td><td>91.88.224.5</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                        <tr><td>RDESX001</td><td>197.188.15.93</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                        <tr><td>RDESX002</td><td>168.85.154.251</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                        <tr><td>RDESX003</td><td>209.25.191.61</td><td><span tooltip="Server Down!" class="text-danger ng-scope"><i class="fa fa-warning"></i></span></td></tr>
                        <tr><td>RDESX004</td><td>252.37.192.235</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                        <tr><td>RDTerminal01</td><td>139.71.18.207</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                        <tr><td>RDTerminal02</td><td>136.80.122.212</td><td><span tooltip="Could not connect!" class="text-warning ng-scope"><i class="fa fa-flash"></i></span></td></tr>
                        <tr><td>RDDomainCont01</td><td>196.80.245.33</td><td><span class="text-success"><i class="fa fa-check"></i></span></td></tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="widget">
                <div class="widget-title">
                  <i class="fa fa-users"></i> Users
                  <input type="text" placeholder="Search" class="form-control input-sm pull-right">
                  <div class="clearfix"></div>
                </div>
                <div class="widget-body medium no-padding">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr><th class="text-center">ID</th><th>Username</th><th>Role</th><th>Account</th></tr>
                      </thead>
                      <tbody>
                        <tr><td class="text-center">1</td><td>Joe Bloggs</td><td>Super Admin</td><td>AZ23045</td></tr>
                        <tr><td class="text-center">2</td><td>Timothy Hernandez</td><td>Admin</td><td>AU24783</td></tr>
                        <tr><td class="text-center">3</td><td>Joe Bickham</td><td>User</td><td>AM23781</td></tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="widget">
                <div class="widget-title">
                  <i class="fa fa-plus"></i> Extras
                  <button class="btn btn-sm btn-info pull-right">Button</button>
                  <div class="clearfix"></div>
                </div>
                <div class="widget-body">

                  <div class="message">
                    This is a standard message which will also work the ".no-padding" class, I can also <span class="error">be an error message!</span>
                  </div>

                  <hr>

                  <div class="message">
                    <a href="http://angular-ui.github.io/bootstrap/" target="_blank">UI Bootstrap</a> is included, so you can use <a href="#" tooltip="I'm a tooltip!" class="ng-scope">tooltips</a> and all of the other native Bootstrap JS components!
                  </div>

                  <hr>

                  <form class="form-horizontal ng-pristine ng-valid" role="form">
                    <div class="form-group has-feedback has-success">
                      <label for="label" class="col-sm-2 control-label">Inline Form</label>
                      <div class="col-sm-5">
                        <input type="text" class="form-control">  
                          <span class="fa fa-key form-control-feedback"></span>
                      </div>
                      <div class="col-sm-5">
                        <div class="input-mask">I'm an input mask!</div>
                      </div>
                      <div class="row">
                        <div class="col-sm-offset-2 col-sm-10">
                          <span class="help-block form-group-inline-message">I'm a properly padded inline message!</span>
                        </div>
                      </div>
                    </div>
                  </form>

                </div>
              </div>
            </div>

          </div>

-->
        <!-- End Main Content -->

      </div><!-- End Page Content -->
    </div><!-- End Content Wrapper -->
  </div><!-- End Page Wrapper -->

</body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackmit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/new.html.erb
<html lang="en" ng-app="Dashboard" class="ng-scope"><head><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-animate){display:none !important;}ng\:form{display:block;}</style>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Dashboard</title>

  <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="/assets/fonts/font-awesome.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/dashboard/dashboard.css">
  <link rel="stylesheet" type="text/css" href="css/themes/blue.css">
  <!--
  <link rel="stylesheet" type="text/css" href="css/themes/green.css">
  <link rel="stylesheet" type="text/css" href="css/themes/red.css">
  -->

  <script type="text/javascript" src="js/angular.min.js"></script>
  <script type="text/javascript" src="js/angular-cookies.js"></script>
  <script type="text/javascript" src="js/ng-bootstrap-tpls.min.js"></script>
  <script type="text/javascript" src="js/angular/bootstrap.js"></script>

</head>
<body ng-controller="MasterCtrl" class="ng-scope">

    <!-- Fixed navbar -->
      <div id="navigation" class="navbar navbar-default navbar-fixed-top" style="border-bottom: 3px solid #e7e7e7;">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><b>Backito</b></a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
          <li><%= link_to 'Home', welcome_index_path%></li>
            <li><%= link_to 'Edit', edit_user_registration_path%></li>
            <li   class="active"><%= link_to 'Projects', 'proj'%></li>
            
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>

              

        </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>


  <div id="page-wrapper" ng-class="{'active': toggle}" class="active">

    <!-- Sidebar -->

    <div id="sidebar-wrapper">
      <ul class="sidebar">
        <li class="sidebar-title"><span>CAMPAIGNS</span></li>
        <li class="sidebar-list">
          <a href="/proj">My Campaigns <span class="menu-icon fa fa-tachometer"></span></a>
        </li>
        <li class="sidebar-list">
          <a href="/projs">New Campaign<span class="menu-icon fa fa-tasks"></span></a>
        </li>
        <li class="sidebar-list">
          <a href="#">Settings <span class="menu-icon fa fa-cogs"></span></a>
        </li>
        <li class="sidebar-title separator"><span>QUICK LINKS</span></li>
        <li class="sidebar-list">
          <a href="#" target="_blank">Forums <span class="menu-icon fa fa-external-link"></span></a>
        </li>
      </ul>
      <div class="sidebar-footer">
        <div class="col-xs-4">
          <a href="https://github.com/Ehesp/Responsive-Dashboard" target="_blank">
            Github
          </a>
        </div>
        <div class="col-xs-4">
          <a href="#" target="_blank">
            About
          </a>
        </div>
        <div class="col-xs-4">
          <a href="#">
            Support
          </a>
        </div>
      </div>
    </div>

    <!-- End Sidebar -->

    <div id="content-wrapper">
      <div class="page-content">

        <!-- Header Bar -->

        <div class="row header">
          <div class="col-xs-12">
            <div class="meta pull-left">
              <div class="page">
                Dashboard
              </div>
              <div class="breadcrumb-links">
                Home / Dashboard
              </div>
            </div>
            <div class="user pull-right">
              <div class="item dropdown">
                <a href="#" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">
                  <img src="img/avatar.jpg">
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    Joe Bloggs
                  </li>
                  <li class="divider"></li>
                  <li class="link">
                    <a href="#">
                      Profile
                    </a>
                  </li>
                  <li class="link">
                    <a href="#">
                      Menu Item
                    </a>
                  </li>
                  <li class="link">
                    <a href="#">
                      Menu Item
                    </a>
                  </li>
                  <li class="divider"></li>
                  <li class="link">
                    <a href="#">
                      Logout
                    </a>
                  </li>
                </ul>               
              </div>
              <div class="item dropdown">
               <a href="#" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-bell-o"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    Notifications
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="#">Server Down!</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
    <div class="container">

<%= form_for :project, url: projects_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

   <p>
    <%= f.label :exp %><br>
    <%= f.date_field :exp %>
  </p>

  <%= f.label :target %><br>
    <%= f.text_field :target %>
  </p>


  <%= f.label :ethercode %><br>
    <%= f.text_field :ethercode %>
  </p>

   <p>
    <%= f.label :roll %><br>
    <%= f.date_field :roll %>
  </p>

  <p>
    <%= f.label :min %><br>
    <%= f.text_field :min %>
  </p>

 
  <p>
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>






</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
  </body>
</html>